wandb_version: 1

exp_name:
  desc: null
  value: CleanRL
seed:
  desc: null
  value: 1
torch_deterministic:
  desc: null
  value: true
cuda:
  desc: null
  value: true
track:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: SAC
wandb_entity:
  desc: null
  value: phdminh01
capture_video:
  desc: null
  value: true
env_id:
  desc: null
  value: LunarLander-v2
total_timesteps:
  desc: null
  value: 500000
buffer_size:
  desc: null
  value: 300000
gamma:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 0.005
batch_size:
  desc: null
  value: 256
learning_starts:
  desc: null
  value: 10000
policy_lr:
  desc: null
  value: 0.0003
q_lr:
  desc: null
  value: 0.001
policy_frequency:
  desc: null
  value: 1
target_network_frequency:
  desc: null
  value: 1
autotune:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    code_path: code/CleanRL.py
    python_version: 3.10.13
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705443877.954517
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.10.13
      5: 0.16.2
      8:
      - 4
      - 5
      13: darwin-arm64
