wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/PPOContinuous.py
    python_version: 3.10.13
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705180675.909784
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 23
      - 35
      4: 3.10.13
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
